name: Workflows

on: [push]

jobs:
  ToxTests:
    steps:
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libboost-all-dev swig
      - uses: Somerandomguy10111/devops/actions/basepy@main
      - uses: Somerandomguy10111/devops/actions/toxtests@main
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libboost-all-dev swig
      - uses: Somerandomguy10111/devops/actions/basepy@main
      - uses: Somerandomguy10111/devops/actions/deptry@main
