name: Workflows

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libboost-all-dev swig

  StdPyTests:
    needs: setup-env  # Ensures setup-env runs first
    uses: Somerandomguy10111/devops/.github/workflows/stdpy.yml@main